<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Tuesday 12th of November 2013 06:24:14 AM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		//"base_url" => "http://192.73.233.169/skedulus/hybridauth/", 
		"base_url" => "http://dev.eulogik.com/skedulus/hybridauth/",

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => true
			),

			"AOL"  => array ( 
				"enabled" => true 
			),

			"Yahoo" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" )
			),
			
			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "621730091219129", "secret" => "79ca77bfacfaaa29747bade2b91c8a42" ) 
			),

			"Twitter" => array ( 
				"enabled" => true,
				"scope"=>"email",	
				"keys"    => array ( "key" => "8kE4nyONJcck7bjzLxrMw", "secret" => "luSDMPtlcJUMK9V5kmdqjKwFoIIoYX4Foj0HuGmrfw" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"Foursquare" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => "world.txt"
	);
